[Onpress]
shorthand = '[string] Url to navigate to'
keys = [
    {name = 'href', before_prefill = 'https://', prefill = "url", type = 'string', description = 'The url or dashboard to navigate to'},
    {name = 'target', prefill = ['this_tab', 'new_tab', 'iframe', 'dashboard'], type = 'string', description = 'Open the url in this tab, a new tab, or iframe, or navigate to a dashboard'},
]

[Image]
shorthand = '[string] path to image or material icon name'
keys = [
    {name = 'type', prefill = ['image', 'material-icon'], type = 'string', description = 'What type of image/icon set to use.'},
    {name = 'src', prefill = ['/static/images/apps/default.png', '/static/user_assets/images/default.png', 'material_icon_name', 'https://', 'http://'], type = 'string', description = 'path to image if image, material icon name if material icon'},
    {name = 'height', prefill = ['64px', '2rem', '10%'], type = 'size', description = 'CSS height of the image'}
]

[Action]
keys = [
    {name = 'icon', prefill = "Image", type = 'Image', description = 'The image object for the action'},
    {name = 'onpress', prefill = "Onpress", type = 'Onpress', description = 'The onpress object for the action'},
]

[ListItem]
keys = [
    {name = 'icon', prefill = "Image", type = 'Image', description = 'The image object for the list item avatar'},
    {name = 'name', prefill = "", type = 'string', description = 'Name of the list item, text to the right of icon'},
    {name = 'onpress', prefill = "Onpress", type = 'Onpress', description = 'The onpress object for the list item'},
    {name = 'classes', prefill = "", type = 'classes', description = ''},
    {name = 'css', prefill = "", type = 'css', description = ''},
]